PATH_TO_DATABASE = "database/"
PATH_TO_ERROR_LOG = "telegram_logic/"

DATABASE_NAME = "database.db"
ERROR_LOG_NAME = "error_log.txt"

SUPER_ADMIN = "SUPER_ADMIN"
ADMIN = "ADMIN"
USER = "USER"
UNAUTHORIZED_TELEGREM_ID = -1
